export class Role {
  id: string;
  rolename: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date;
  version: number;

  constructor(rolename: string) {
    this.id = `uuid-${rolename}`;  // fake uuid autogenerated
    this.rolename = rolename;
    this.createdAt = new Date();
    this.updatedAt = new Date();
    this.deletedAt = new Date();
    this.version = 1;
  }

}