import { ICartItem } from './../../state-shopping-cart/interfaces/cart-item.interface';
export class Sell {
  id: string;
  userId: string;
  items: ICartItem[];
  state: 'pending' | 'transporting' | 'delivered';
  totalCost: number;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date;
  version: number;

  constructor(items: ICartItem[], userId: string) {
    const autoGenId = `${Math.random() * 10}`.replace('.', '');
    this.id = `uuid-${autoGenId}`;  // fake uuid autogenerated
    this.userId = userId;
    this.items = items;
    this.state = 'pending';
    this.createdAt = new Date();
    this.updatedAt = new Date();
    this.deletedAt = new Date();
    this.version = 1;
    this.totalCost = 0;
    for (const item of items) {
      this.totalCost += item.price * item.amount;
    }
  }

}