export class User {
  id: string;
  username: string;
  email: string;
  password: string;
  roles: string[] = [];
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date;
  version: number;

  constructor(username: string, password: string, email: string, roles: string[]) {
    const autoGenId = `${Math.random() * 10}`.replace('.', '');
    this.id = `uuid-${autoGenId}`;  // fake uuid autogenerated
    this.username = username;
    this.email = email;
    this.password = password;
    this.roles = roles;
    this.createdAt = new Date();
    this.updatedAt = new Date();
    this.deletedAt = new Date();
    this.version = 1;
  }

}